package facade.util;

public interface TherapyGameConstants
{
    public static final int eTherapyGame_who_none = -1;
    public static final int eTherapyGame_who_grace = 0;
    public static final int eTherapyGame_who_trip = 1;
    public static final int eTherapyGame_who_graceOrTrip = 2;
    public static final int eTherapyGame_who_any = 3;
    public static final int eTherapyGame_mood_GAngry = 0;
    public static final int eTherapyGame_mood_GSad = 1;
    public static final int eTherapyGame_mood_GFurious = 2;
    public static final int eTherapyGame_mood_GUpset = 3;
    public static final int eTherapyGame_mood_TAngry = 4;
    public static final int eTherapyGame_mood_TSad = 5;
    public static final int eTherapyGame_mood_TFurious = 6;
    public static final int eTherapyGame_mood_TUpset = 7;
    public static final int eTherapyGame_pp_past = 0;
    public static final int eTherapyGame_pp_present = 1;
    public static final int eTherapyGame_mixinType_test = 0;
    public static final int eTherapyGame_mixinType_redirect = 1;
    public static final int eTherapyGame_mixinType_cajole = 2;
    public static final int eTherapyGame_mixinType_strongMood = 3;
    public static final int eTherapyGame_mixinType_shortCustom = 4;
    public static final int eTherapyGame_mixinType_repeatVersion = 5;
    public static final int eTherapyGame_mixinType_accusation = 6;
    public static final int eTherapyGame_mixinType_miscAutonomous = 7;
    public static final int eTherapyGame_charFocus_none = -1;
    public static final int eTherapyGame_charFocus_grace = 0;
    public static final int eTherapyGame_charFocus_trip = 1;
    public static final int eTherapyGame_charFocus_relationship = 2;
    public static final int eTherapyGame_availability_available = 0;
    public static final int eTherapyGame_availability_used = 1;
    public static final int eTherapyGame_repeatCategory_none = -1;
    public static final int eTherapyGame_repeatCategory_trueMajorMinor = 0;
    public static final int eTherapyGame_repeatCategory_falseMajorMinor = 1;
    public static final int eTherapyGame_repeatCategory_falseDysfunctional = 2;
    public static final int eTherapyGame_repeatCategory_satellite = 3;
    public static final int eTherapyGame_repeatCategory_graceObj = 4;
    public static final int eTherapyGame_repeatCategory_tripObj = 5;
    public static final int eTherapyGame_repeatCategory_praiseEtcG = 6;
    public static final int eTherapyGame_repeatCategory_praiseEtcT = 7;
    public static final int eTherapyGame_repeatCategory_hugEtcG = 8;
    public static final int eTherapyGame_repeatCategory_hugEtcT = 9;
    public static final int eTherapyGame_repeatCategory_critEtcG = 10;
    public static final int eTherapyGame_repeatCategory_critEtcT = 11;
    public static final int eTherapyGame_repeatCategory_thrownOut = 12;
    public static final int eTherapyGame_gaze_default = -1;
    public static final int eTherapyGame_gaze_player = 0;
    public static final int eTherapyGame_postAskPlayer_none = -1;
    public static final int eTherapyGame_postAskPlayer_aboutMe = 0;
    public static final int eTherapyGame_postAskPlayer_aboutSpouse = 0;
}
